// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn7s83Ogyo7AyNpfTXUN_LXa8YhfNj1W8',
    appId: '1:244194186757:android:2945ed466fb46f7f356e6c',
    messagingSenderId: '244194186757',
    projectId: 'your-fuel',
    storageBucket: 'your-fuel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4LmCSaOTSY_svOrzmWWoYcnCEJd7b7k',
    appId: '1:244194186757:ios:c5b98f9caae7f1dd356e6c',
    messagingSenderId: '244194186757',
    projectId: 'your-fuel',
    storageBucket: 'your-fuel.appspot.com',
    androidClientId: '244194186757-0nlo98elgifs7j41l819jhcb3t0d94g1.apps.googleusercontent.com',
    iosClientId: '244194186757-7fl3r9ll1uo5n24j6tsv14pevlsdmn4o.apps.googleusercontent.com',
    iosBundleId: 'com.app.yourfuel',
  );
}
